modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://modrinth.com/user/pycodder"

[[mods]]
modId = "reanimated"
version = "1.0.0"
displayName = "ReAnimated"
authors = "pycodder"
logoFile = "icon.png"
description = '''
Плавные анимации для всего интерфейса Minecraft: заставка, кнопки, меню, контейнеры и инвентарь.'''

[[mixins]]
config = "reanimated.mixins.json"

[[dependencies.reanimated]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.reanimated]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "CLIENT"
