org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric / Minecraft (26.2 — деобфусцированная эпоха, без yarn)
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_version=0.153.0+26.1.2

mod_version=26.1.2+1.6
maven_group=com.pycodder
archives_base_name=reanimated
modmenu_version=18.0.0-beta.1
sodium_version=mc26.1.2-0.9.1-fabric
